spring:
  application:
    name: eureka-client
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/app
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-request-size: 209715200
      max-file-size: 209715200
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
